run:
  go: 1.24.0
  timeout: 5m
  tests: true
  build-tags: []

linters:
  disable-all: true
  enable:
    - errcheck        # Detects unchecked errors
    - gosimple        # Suggests code simplification
    - govet           # Go's static analyzer
    - ineffassign     # Detects ineffective assignments
    - staticcheck     # Advanced static analysis
    - typecheck       # Type checking
    - unused          # Detects unused code
    - gocyclo         # Detects code complexity
    - gofmt           # Standard formatter
    - gosec           # Security checker
    - bodyclose       # Detects missing body close
    - goconst         # Detects duplicate code
    - gci             # Go code cleaner
    - nestif          # Detects nested if statements
    - lll             # Detects long lines
    - nlreturn        # Detects redundant return statements
    - predeclared     # Detects predeclared identifiers
    - tagliatelle     # Detects unused tags
    - goimports       # Organizes imports
    - misspell        # Detects spelling mistakes
    - revive          # Alternative to golint
    - whitespace      # Detects redundant whitespace
    - prealloc        # Suggests slice preallocation
    - gocritic        # Provides many diagnostics
    - godot           # Checks comment endings
    - nolintlint      # Reports ill-formed nolint directives

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
      - name: error-naming
        severity: warning
  gofmt:
    simplify: true
  lll:
    line-length: 140
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  nestif:
    min-complexity: 4
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - lll
    - path: cmd/
      linters:
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
