# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

project_name: airules

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/hashiiiii/airules/pkg/version.Version={{.Version}}
      - -X github.com/hashiiiii/airules/pkg/version.Commit={{.Commit}}
      - -X github.com/hashiiiii/airules/pkg/version.BuildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: airules
    repository:
      owner: hashiiiii
      name: homebrew-tap
    homepage: "https://github.com/hashiiiii/airules"
    description: "AI Editor rules Installer"
    license: "MIT"
    install: |
      bin.install "airules"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
