name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.24']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        
    - name: Test
      run: go test -v ./pkg/...
      
    - name: Generate coverage report (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        go test -coverprofile=coverage.out ./pkg/...
        go tool cover -func=coverage.out
      
    - name: Generate coverage report (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        go test -coverprofile=coverage.out ./pkg/...
        go tool cover -func=coverage.out
      shell: bash
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-${{ matrix.os }}
        path: coverage.out
